//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceBill
    {
        public int Quantity { get; set; }
        public int BillID { get; set; }
        public int DeviceID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Device Device { get; set; }
    }
}
